# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/nlphomepage/public_html/
#     - /bin/rsync -az --delete --exclude=".git*" --exclude=".cpanel.yml" ./ $DEPLOYPATH

---
deployment:
  tasks:
    - export SRCPATH=/home/nlphomepage/repositories/uiuc-nlp-website/
    - export DEPLOYPATH=/home/nlphomepage/public_html/

    # publish
    - /bin/rsync -az --delete --delete-excluded --force \
        --exclude=".git*" --exclude=".cpanel.yml" \
        "$SRCPATH" "$DEPLOYPATH"

    # fix perms every time
    - /bin/chmod 755 "$DEPLOYPATH"
    - /bin/find "$DEPLOYPATH" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} \;